### ISSUE TITLE
module 'torch.onnx' has no attribute 'OperatorExportTypes'

### ISSUE THREAD

**Issue by achanger** [waleedka/hiddenlayer#10]
I run this code in Jupyter Notebook，but one error occurs:
`
import torch

import torchvision.models

import hiddenlayer as hl

model = torchvision.models.vgg16()

hl.build_graph(model, torch.zeros([1, 3, 224, 224]))

`

AttributeError: module 'torch.onnx' has no attribute 'OperatorExportTypes'

And I run the code under Ubuntu16.04, pytorch 0.4.0

**Comment by DolphinAC** [comment]
hi，the same error occurs. Do you know how to solve this problems?

**Comment by waleedka** [comment]
I haven't encountered this issue, but could it be an issue with Pytorch version? The library was tested on PyTorch 0.4.1

**Comment by jiaobingle** [comment]
@achanger have you solved the issue with pytorch 0.4.1 , thx!

**Comment by DolphinAC** [comment]
@jiaobingle Yes

**Comment by plet1** [comment]
> I haven't encountered this issue, but could it be an issue with Pytorch version? The library was tested on PyTorch 0.4.1

I have another question. 
Now, I have three input with [ 32,6,  25, 25], [ 32,6,  51, 51],[32, 6,  75, 75]. How do I do ? 
I also, hl.build_graph(net, torch.zeros(
     [ 32,6,  25, 25],
    [ 32,6,  51, 51],
    [32, 6,  75, 75]
)) 
But my code had error: TypeError: zeros(): argument 'out' (position 2) must be Tensor, not list
Thank you.
