### ISSUE TITLE
how can I show graph if don't use jupyter notebook

### ISSUE THREAD

**Issue by aikudexiaohai** [waleedka/hiddenlayer#13]

**Comment by achanger** [comment]
model = torchvision.models.vgg16()
hl_graph = hl.build_graph(model, torch.zeros([1, 3, 224, 224]))
hl_graph.save("xxx", format="png")

**Comment by philferriere** [comment]
Hi @aikudexiaohai,

If the information provided above doesn't answer your question or you're still facing issues, feel free to add more details to this thread and re-open this issue.

Thanks!
