### ISSUE TITLE
Shape visualization problem

### ISSUE THREAD

**Issue by wuyxiquanquan** [waleedka/hiddenlayer#16]
Hi:
    Thank you for you amazing work! But I have a problem about the visualization:How can I get more shape info? Can you tell me the solution?
best,
yuxiang
     
![vgg11 3](https://user-images.githubusercontent.com/40594739/48538804-6939f080-e8f0-11e8-8a51-32d25607bdfd.png)

**Comment by waleedka** [comment]
Thanks for reporting this. I tracked the problem and just pushed a fix. Please get the latest from Github and that issue should be solved.
