### ISSUE TITLE
import hiddenlayer Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by husencd** [waleedka/hiddenlayer#17]
I tried to install hiddenlayer using pip and install it from source code, respectively. But when i import hiddenlayer, i met an error, wich is `Segmentation fault (core dumped)`.

Do you have any idea about this bug?

**Comment by waleedka** [comment]
Typically, Python code doesn't cause a segmentation fault. My best guess is that the error is happening in one of the imported libraries that include binary code. It could be TensorFlow, PyTorch, GraphViz, ...etc. Try this: create a new Python file, and in it put only one `import` statement to import each of the libraries, one at a time, and see which causes the code to fail.

**Comment by philferriere** [comment]
Hi @husencd,

If the information provided above doesn't answer your question or you're still facing issues, feel free to add more details to this thread and re-open this issue.

Thanks!
