### ISSUE TITLE
BUG report: the stable version on pip has a bug

### ISSUE THREAD

**Issue by luzhilin19951120** [waleedka/hiddenlayer#18]
Hi there~

Your stable version on pip has a bug.

line 324 in graph.py 
dot.attr("edge", style="doted",

would cause Error:
__Warning: gvrender_set_style: unsupported style doted - ignoring__

which was terribly annoying. And caused me lots of time debugging.

We found that you spell the dotted wrongly..., it should be "dotted" instead of "doted". And we also found that you had updated the code into "solid" on github...

We hope you guys update [the pip package](https://pypi.org/) as soon as possible because the bug is really too funny ^_^.

**Comment by waleedka** [comment]
Done! The latest version from master is now on PyPI as version 0.2.
