### ISSUE TITLE
Horizontal view ?

### ISSUE THREAD

**Issue by theevann** [waleedka/hiddenlayer#24]
Is it possible to get a horizontal view of the network graph ?

**Comment by waleedka** [comment]
Yes. Find the `build_dot()` method in `graph.py`. There it creates the dot object and sets its attributes for the graph level, node level, and edge level. Add `rankdir="LR"` to the attributes at the graph level. That should do it.

**Comment by paland3** [comment]
Just to make it easy for anyone who finds this later:

```
graph = hl.build_graph(model, torch.zeros([1, 1, 64, 64, 64]))
dot=graph.build_dot()
dot.attr("graph", rankdir="TD") #Topdown
dot.attr("graph", rankdir="LR") #Left-Right
```

**Comment by waleedka** [comment]
Thanks, @paland3 . That's a better solution than the one I suggested.
