### ISSUE TITLE
TypeError: zeros(): argument 'out' (position 2) must be Tensor, not list

### ISSUE THREAD

**Issue by plet1** [waleedka/hiddenlayer#28]
I want to visualizer a model with 3-input and have problem with feed 3-input. This model have three input, this filgure:
![image](https://user-images.githubusercontent.com/37217354/52959983-b309fb00-3365-11e9-91c2-cc4939f0418c.png)

I conferenced this ideal of Waleed (https://github.com/waleedka)and I visualier 3 patch with 3 input           [ 32,6, 25, 25] [ 32,6, 51, 51],[32, 6, 75, 75] with code line: 

hl.build_graph(model, torch.zeros([32,6,  25, 25], [32,6, 51, 51],[32, 6, 75, 75]))

1) _**But my code had the error: TypeError: zeros(): argument 'out' (position 2) must be Tensor, not list.**_
**_How do I fix this problem?_** (I also tried many ways, example: 
#hl.build_graph(net, torch.zeros( 32,6,  25, 25), torch.zeros(32, 6, 51, 51), torch.zeros(32, 6, 75, 75))
#hl.build_graph(net, torch.zeros(( 32,6,  25, 25), ( 32,6,  51, 51), ( 32,6,  75, 75)))
#hl.build_graph(net, torch.zeros([( 32,6,  25, 25)],[( 32,6,  51, 51)],[( 32,6,  75, 75)])
)

In addition, I successed with the first path with code line: 
hl.build_graph(model, torch.zeros([32,6,  25, 25]). And had figure: 
![image](https://user-images.githubusercontent.com/37217354/52960603-282a0000-3367-11e9-8ae2-f22b6113fb62.png).....................
2) And question more about **_window size_** of model visualize. **_Can we show full model visualize one window or save it ?_** as we see these below picture, I must to stride many time in oder to take a my model.

![image](https://user-images.githubusercontent.com/37217354/53017530-2ff8ab80-341e-11e9-9b33-6e2a8a39ee24.png)
![image](https://user-images.githubusercontent.com/37217354/53017554-40108b00-341e-11e9-95e8-89743efc94b6.png)

Thank you.

**Comment by plet1** [comment]
I had a solution:
input_1 = torch.zeros([......])
input_2 = torch.zeros([......])
hl.build_graph(..., (input1, input2, ...,input_n))

Thank you, all.

**Comment by waleedka** [comment]
Thanks for posting the answer. I'll close this issue then.
