### ISSUE TITLE
adaptive_avg_pool2d does not exist

### ISSUE THREAD

**Issue by zhouyuangan** [waleedka/hiddenlayer#6]
Hi, I met this problem when I want to visualize densenet, error shows below:
`c:\python35\lib\site-packages\torch\onnx\utils.py:446: UserWarning: ONNX export failed on ATen operator adaptive_avg_pool2d because torch.onnx.symbolic.adaptive_avg_pool2d does not exist
  .format(op_name, op_name))`
Actually, there is no adaptive_avg_pool2d in my densenet, only nn.AvgPool2d() exists.

**Comment by zhouyuangan** [comment]
Sorry. 
It's my mistake that I forget I have add [senet module](https://arxiv.org/abs/1709.01507) which contains [adaptive_avg_pool2d](https://github.com/zhouyuangan/SE_DenseNet/blob/88e09d62cdb9f475771d096804188c722b0cb942/se_module.py#L8) in densenet.

**Comment by waleedka** [comment]
No worries. Closing this issue then.

**Comment by John1231983** [comment]
How about it?
```
/home/join/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py:501: UserWarning: ONNX export failed on ATen operator adaptive_avg_pool3d because torch.onnx.symbolic.adaptive_avg_pool3d does not exist
```
