### ISSUE TITLE
'torch._C.Value' object has no attribute 'uniqueName'

### ISSUE THREAD

**Issue by woodg07** [waleedka/hiddenlayer#64]
import torch
    import torchvision.models
    import hiddenlayer as hl
    # VGG16 with BatchNorm
    model = torchvision.models.vgg16()

    # Build HiddenLayer graph
    # Jupyter Notebook renders it automatically
    hl.build_graph(model, torch.zeros([1, 3, 224, 224]))

python 3.6
torch 1.3.1
hl 0.2

AttributeError                            Traceback (most recent call last)
<ipython-input-4-df97773ffa77> in <module>
      7 # Build HiddenLayer graph
      8 # Jupyter Notebook renders it automatically
----> 9 hl.build_graph(model, torch.zeros([1, 3, 224, 224]))

~/anaconda3/envs/py36/lib/python3.6/site-packages/hiddenlayer-0.2-py3.6.egg/hiddenlayer/graph.py in build_graph(model, args, input_names, transforms, framework_transforms)
    141         from .pytorch_builder import import_graph, FRAMEWORK_TRANSFORMS
    142         assert args is not None, "Argument args must be provided for Pytorch models."
--> 143         import_graph(g, model, args)
    144     elif framework == "tensorflow":
    145         from .tf_builder import import_graph, FRAMEWORK_TRANSFORMS

~/anaconda3/envs/py36/lib/python3.6/site-packages/hiddenlayer-0.2-py3.6.egg/hiddenlayer/pytorch_builder.py in import_graph(hl_graph, model, args, input_names, verbose)
     88         shape = get_shape(torch_node)
     89         # Add HL node
---> 90         hl_node = Node(uid=pytorch_id(torch_node), name=None, op=op, 
     91                        output_shape=shape, params=params)
     92         hl_graph.add_node(hl_node)

~/anaconda3/envs/py36/lib/python3.6/site-packages/hiddenlayer-0.2-py3.6.egg/hiddenlayer/pytorch_builder.py in pytorch_id(node)
     43     # After ONNX simplification, the scopeName is not unique anymore
     44     # so append node outputs to guarantee uniqueness
---> 45     return node.scopeName() + "/outputs/" + "/".join([o.uniqueName() for o in node.outputs()])
     46 
     47 

~/anaconda3/envs/py36/lib/python3.6/site-packages/hiddenlayer-0.2-py3.6.egg/hiddenlayer/pytorch_builder.py in <listcomp>(.0)
     43     # After ONNX simplification, the scopeName is not unique anymore
     44     # so append node outputs to guarantee uniqueness
---> 45     return node.scopeName() + "/outputs/" + "/".join([o.uniqueName() for o in node.outputs()])
     46 
     47 

AttributeError: 'torch._C.Value' object has no attribute 'uniqueName'

**Comment by mydmdm** [comment]
try to fix it in #69

**Comment by jaewooklee93** [comment]
Is it still not be fixed? 

I should downgrade my PyTorch 1.3.1 to older one..

**Comment by sizhky** [comment]
code ran with latest pytorch when I cloned and pip installed #69

**Comment by waleedka** [comment]
Issue fixed and verified on PyTorch 1.5
