### ISSUE TITLE
module 'torch.jit' has no attribute '_get_trace_graph'

### ISSUE THREAD

**Issue by zhongqiu1245** [waleedka/hiddenlayer#79]
Hi，thank you for your amazing job
I try to use your work to visualize my own model
When I run :
#my model
import hiddenlayer as hl
hl.build_graph(model, torch.zeros([1, 3, 224, 224]))
but I got:
AttributeError: module 'torch.jit' has no attribute '_get_trace_graph'
Could you tell me how can I slove it?
Thank you

**Comment by ischihmo** [comment]
https://github.com/microsoft/tensorwatch/issues/29#issuecomment-596304208

**Comment by benihime91** [comment]
I am getting the same error.

**Comment by austinmw** [comment]
@zhongqiu1245 Hi, how did you solve this?
