### ISSUE TITLE
How to display branch nodes / parallel blocks

### ISSUE THREAD

**Issue by talhaanwarch** [waleedka/hiddenlayer#86]
I am confused about how to transform the following structure which has branches coming out from a node.
This is what I tried
`hl.transforms.Fold("""Conv > LeakyRelu > Conv > Concat > LeakyRelu """, "Fire","FireBlock")`

![image](https://user-images.githubusercontent.com/37379131/110212611-048a7180-7ebe-11eb-8c7b-38479cec1ae3.png)

**Comment by HaoLuo2627** [comment]
I find this in demos:
And the expressions `Conv | MaxPool` will match any Conv and MaxPool layers that are in parallel branches (i.e. have the same parent node).
So I think """Conv > LeakyRelu > (Conv | Conv) > Concat > LeakyRelu """ may work.

**Comment by talhaanwarch** [comment]
Thanks. It worked.
